### ISSUE TITLE
refactor and document

### ISSUE THREAD

**Issue by thor314** [thor314/hackmd-obsidian#2]

**Comment by Ki-HH** [comment]
Hello,
I'd love to try your plugin but I can't make it sync with my HackMD.
Can you explain, what exactly should be done to push a file from obsidian to HackMD.io or maybe paste a screenshot. I am not sure if the error is on my side.

Thanks a lot

**Comment by Ki-HH** [comment]
Now it is magically working.
I just added a new API token.

Thanks!
